<?xml version="1.0"?>
<package format="3">
  <name>d1max_scan_planner</name>
  <version>0.1.0</version>
  <description>D1 Max input and visualization integration for SCAN-Planner.</description>
  <maintainer email="dndx@localhost.localdomain">dndx</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>scan_planner</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
