cmake_minimum_required(VERSION 3.22)
project(d1max_mola_live LANGUAGES CXX)
find_package(mola_lidar_odometry REQUIRED)
find_package(mola_pose_list REQUIRED)
find_package(mola_imu_preintegration REQUIRED)
find_package(mola_input_rosbag2 REQUIRED)
find_package(mola_state_estimation_simple REQUIRED)
find_package(mrpt-tclap REQUIRED)
find_package(Threads REQUIRED)
add_executable(d1max-mola-lidar-cli "${GENERATED_CLI}")
target_compile_features(d1max-mola-lidar-cli PRIVATE cxx_std_17)
target_include_directories(d1max-mola-lidar-cli PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}")
target_compile_definitions(d1max-mola-lidar-cli PRIVATE HAVE_MOLA_INPUT_ROSBAG2 HAVE_MOLA_SE_SIMPLE)
target_link_options(d1max-mola-lidar-cli PRIVATE "LINKER:-rpath-link,${PRIVATE_RUNTIME_LIB}")
target_link_libraries(d1max-mola-lidar-cli PRIVATE mola::mola_lidar_odometry mola::mola_input_rosbag2 mola::mola_state_estimation_simple mrpt::tclap Threads::Threads)
install(TARGETS d1max-mola-lidar-cli RUNTIME DESTINATION bin)
