// Mutating browser QA is restricted to an explicitly isolated fixture backend.
import assert from 'node:assert/strict'
import { createHash } from 'node:crypto'
import { dirname } from 'node:path'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { chromium } from '/home/dndx/go2_nav/tools/map_manager/frontend/node_modules/playwright-core/index.mjs'
const base=process.env.D1MAX_QA_URL||'http://127.0.0.1:8767'
const health=await fetch(base+'/api/health').then(r=>r.json())
assert(health.maps_root.startsWith('/tmp/d1max-web-migration-'),'Refusing to mutate non-fixture maps')
const get=path=>fetch(base+path).then(r=>{assert(r.ok,path);return r.json()})
const overview=()=>get('/api/2d/overview')
// Previous failed QA runs may leave fixture versions; never clean production data.
const initial=await overview()
assert(!initial.job.running,'Fixture has an in-flight build')
assert(initial.versions.every(v=>v.name.startsWith('UI QA')),'Refusing to delete unrecognized fixture versions')
if(initial.selected_id)await fetch(base+'/api/2d/selection',{method:'DELETE'})
for(const version of initial.versions)await fetch(base+'/api/2d/versions/'+version.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({archived:true})})
if(initial.versions.length){
 const response=await fetch(base+'/api/2d/archive/delete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({version_ids:initial.versions.map(v=>v.id)})})
 assert(response.ok)
}
const raw=await get('/api/overview'),source=raw.items.find(v=>v.extension==='pcd')
assert(source)
const hash=async path=>createHash('sha256').update(await readFile(path)).digest('hex')
const sourceHash=await hash(source.path), report={checks:[],screenshots:[],errors:[]}
const out=process.env.D1MAX_QA_ARTIFACTS||'/tmp/d1max-portal-qa'
await mkdir(out,{recursive:true})
const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']})
const page=await browser.newPage({viewport:{width:1440,height:1000}})
page.on('pageerror',e=>report.errors.push(e.message))
const requests=[];page.on('request',r=>requests.push({url:r.url(),method:r.method()}))
const check=name=>{report.checks.push(name);console.log('PASS '+name)}
const click=name=>page.getByRole('button',{name,exact:true}).click()
const route=async path=>{await page.goto(base+'/#'+path);await page.waitForTimeout(600)}
const poll=async predicate=>{for(let i=0;i<80;i++){const state=await overview();if(predicate(state))return state;await page.waitForTimeout(250)}throw Error('Timed out waiting for grid state')}
try{
 await route('/')
 assert.equal(await page.locator('.workspace-choice').count(),2)
 assert(!requests.some(r=>/PointCloudView|\/preview\?/.test(r.url)))
 check('Homepage has separate 2D / 3D entries and loads no point-cloud renderer')
 await route('/3d/maps')
 await page.locator('canvas').waitFor({state:'visible'})
 await click('建图管理');await page.getByRole('dialog').waitFor();await page.keyboard.press('Escape')
 await click('用此 PCD 生成 2D 地图')
 await page.waitForURL('**/2d/build?source='+source.id)
 assert((await page.getByRole('combobox',{name:'源 PCD',exact:true}).innerText()).includes(source.name))
 await page.getByLabel('版本名称',{exact:true}).fill('UI QA · 原始候选')
 await click('生成并保存候选版')
 let state=await poll(s=>!s.job.running&&s.job.status==='complete')
 const first=state.job.result_id
 assert.equal(state.selected_id,null)
 await page.locator('.grid-inspector-title h2').filter({hasText:'UI QA · 原始候选'}).waitFor()
 check('3D source link preserves ID; 2D build publishes candidate without selecting it')
 await click('修整 2D 地图')
 await page.locator('.map-editor canvas.ready').waitFor()
 await page.getByRole('button',{name:'擦除杂点 标记为可通行'}).click()
 const canvas=await page.locator('.map-editor canvas').boundingBox()
 await page.mouse.move(canvas.x+canvas.width*.2,canvas.y+canvas.height*.2)
 await page.mouse.down();await page.mouse.move(canvas.x+canvas.width*.35,canvas.y+canvas.height*.35,{steps:8});await page.mouse.up()
 await click('撤销');assert(await page.getByRole('button',{name:'保存为新地图版本'}).isDisabled())
 await click('重做')
 await page.getByLabel('新版本名称',{exact:true}).fill('UI QA · 修整版')
 await page.screenshot({path:out+'/editor-desktop.png'});report.screenshots.push('editor-desktop.png')
 await click('保存为新地图版本')
 await page.locator('.map-editor').waitFor({state:'hidden'})
 state=await overview()
 const edited=state.versions.find(v=>v.parent_version===first)
 assert(edited);assert.equal(state.selected_id,null)
 assert.equal(await hash(source.path),sourceHash)
 assert.equal(await hash(dirname(edited.map_yaml_path)+'/localization.pcd'),sourceHash)
 check('Canvas stroke, undo / redo and immutable new-version save work')
 await click('设为选用地图');await click('确认');await poll(s=>s.selected_id===edited.id)
 await page.locator('.grid-version button').filter({hasText:'UI QA · 原始候选'}).click()
 await click('设为选用地图');await click('确认');await poll(s=>s.selected_id===first)
 await click('回退上一版本');await click('确认');await poll(s=>s.selected_id===edited.id)
 check('Explicit selection and rollback update metadata only')
 await page.locator('.grid-version button').filter({hasText:'UI QA · 修整版'}).click()
 const [download]=await Promise.all([page.waitForEvent('download'),page.locator('a[download]').filter({hasText:'下载完整版本'}).click()])
 await download.saveAs(out+'/map-version.zip')
 await click('修改名称');await page.getByLabel('版本名称',{exact:true}).fill('UI QA · 已核对')
 await click('保存名称');await poll(s=>s.versions.some(v=>v.name==='UI QA · 已核对'))
 check('Complete ZIP download and rename work')
 await route('/2d/navigation');assert(await page.getByRole('button',{name:'启动导航 · 尚未接入'}).isDisabled())
 check('Navigation entry truthfully disabled until D1 localization and execution are integrated')
 for(const width of [1920,1440,1280,900,390]){
  await page.setViewportSize({width,height:1000})
  for(const path of ['/','/2d/versions','/2d/build','/3d/maps']){
   await route(path)
   const dimensions=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,width:innerWidth}))
   assert(dimensions.scroll<=dimensions.width,JSON.stringify({path,width,...dimensions}))
   const name=width+'-'+(path.replaceAll('/','_')||'home')+'.png'
   await page.screenshot({path:out+'/'+name});report.screenshots.push(name)
  }
 }
 await route('/2d/versions');await page.getByRole('button',{name:'Toggle Sidebar'}).click()
 await page.getByRole('link',{name:'导航准备',exact:true}).click()
 await page.getByRole('dialog').waitFor({state:'hidden'})
 check('Five viewport widths have no page overflow; mobile navigation closes after selection')
 await page.setViewportSize({width:1440,height:1000});await route('/2d/versions')
 await page.locator('.grid-version button').filter({hasText:'UI QA · 原始候选'}).click()
 await click('无损归档');await poll(s=>s.versions.find(v=>v.id===first).archived)
 await route('/2d/archived');assert.equal(await page.locator('.grid-version').count(),1)
 await page.getByRole('checkbox',{name:'全选2D归档'}).click();await click('删除所选');await click('确认永久删除')
 await poll(s=>!s.versions.some(v=>v.id===first))
 await route('/2d/versions');await click('取消选用');await poll(s=>!s.selected_id)
 await click('无损归档');await poll(s=>s.versions.find(v=>v.id===edited.id).archived)
 await route('/2d/archived');await click('全部删除');await click('确认永久删除')
 await poll(s=>!s.versions.length)
 assert.equal(await hash(source.path),sourceHash)
 check('Archive, selected delete and delete-all remove only fixture versions; raw PCD unchanged')
 await route('/2d/build')
 await page.getByRole('combobox',{name:'2D 参数方案'}).click()
 await page.getByRole('option',{name:'Go2 默认滤波 · 空白设为自由',exact:true}).click()
 assert.equal(await page.getByRole('switch',{name:'启用定位点云预处理'}).getAttribute('aria-checked'),'true')
 await page.getByLabel('版本名称',{exact:true}).fill('UI QA · Go2 滤波')
 await click('生成并保存候选版')
 state=await poll(s=>!s.job.running&&s.job.status==='complete')
 assert(state.versions.some(v=>v.parameters.filter_enabled&&v.free_cells>0))
 await page.locator('.grid-inspector-title h2').filter({hasText:'UI QA · Go2 滤波'}).waitFor()
 await click('无损归档');await poll(s=>s.versions.every(v=>v.archived))
 await route('/2d/archived');await click('全部删除');await click('确认永久删除')
 await poll(s=>!s.versions.length)
 assert.equal(await hash(source.path),sourceHash)
 check('Go2 preset is selectable, executes both filters and produces free-background PGM')
 assert(!requests.some(r=>r.method!=='GET'&&/\/api\/(runtime|control|navigation)/.test(r.url)))
 assert.deepEqual(report.errors,[])
 check('No robot control calls and no browser runtime errors')
}catch(error){report.failure=error.stack;await page.screenshot({path:out+'/failure.png'});throw error}
finally{await writeFile(out+'/report.json',JSON.stringify(report,null,2));await browser.close()}
